name: Deploy to EC2 instance

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        env:
          HOST: 107.20.102.255
          USER: ubuntu
          PATH_TO_APP: /home/ubuntu/app/desafio-votacao-pautas/
        run: |
          ssh -o StrictHostKeyChecking=no $USER@$HOST "
            set -e
            echo 'Starting deployment...'
            export NVM_DIR=\"$HOME/.nvm\"
            [ -d \"$NVM_DIR\" ] || { echo 'NVM directory not found'; exit 1; }
            export PATH=\"$NVM_DIR/versions/node/v20.17.0/bin:\$PATH\"
            . \"$NVM_DIR/nvm.sh\"
            type nvm || { echo 'NVM is still not loaded'; exit 1; }
            nvm install 20
            nvm use 20
            echo 'Navigating to application directory...'
            cd $PATH_TO_APP
            echo 'Fetching latest changes...'
            git fetch origin &&
            git reset --hard origin/main
            echo 'Installing dependencies...'
            npm ci
            npm install -g pm2
            echo 'Building project...'
            npm run build
            echo 'Restarting PM2...'
            pm2 flush
            pm2 restart all
            echo 'Deployment completed successfully.'
          "
